app:
  profile: prod
spring:
  profiles.include: db-prod
logging:
  path: {LOG_PATH}
  file: base
  level:
    kr.com.younsiktech.springboot.base: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
    com.zaxxer.hikari: trace
    com.zaxxer.hikari.HikariConfig: debug
