spring:
  datasource:
    driver-clas-name: com.mysql.cj.jdbc.driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: {id}
    password: {password}
    hikari:
      poolName: SpringBootJPAHikariCP
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: select 1
      maximum-pool-size: 10
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true