spring:
  profiles:
    active: local
  application:
    name: springboot-base
  resources:
    chain:
      html-application-cache: false
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
logging:
  config: classpath:base-logback.xml
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health"]
      base-path: /base
      path-mapping:
        health: /health
server:
  error:
    whitelabel:
      enabled: false
