app:
  profile: prod

base:
  ver:
    api: v1.0
    web: v1.0
  service:
    type:
      service1: service1
      service2: service2
  cache: false

logging:
  path: /home/younsiktech/logs/springboot/base/local
  file: base
  level:
    kr:
      com:
        youunsiktech:
          springboot:
            base: debug