spring:
  profiles:
    active: local
  application:
    name: springboot-base
logging:
  config: classpath:base-logback.xml
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health"]
      base-path: /base
      path-mapping:
        health: /health